# Generated by Django 2.2.11 on 2020-03-11 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='dismissal_type',
            field=models.IntegerField(choices=[(1, 'No Dismissals Allowed'), (2, 'Session Only Dismissal'), (3, 'Permanent Dismissal Allowed')], default=2, verbose_name='dismissal type'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Warning'), (3, 'Critical')], default=1, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='announcements.Announcement', verbose_name='announcement'),
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='dismissed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dismissed at'),
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
